
---
# Configures internal Splunk forwarders

- name: Apply common configuration to all nodes
  hosts: all
  roles:
    - { role: common_centos, tags: ["common"] }

- name: Install and configure syslog-ng with Splunk Forwader
  hosts: syslog-forwarders
  vars_files:
    - cust_vars.yml
  roles:
    - { role: syslog-ng, tags: ["syslog"] }
    - { role: splunk_forwarder, tags: ["splunk"] }