
---

- name: Apply common configuration to all nodes
  hosts: all
  roles:
    - { role: common_centos, tags: ["common"] }

- name: Install Splunk Servers
  hosts: splunk-servers
  vars_files:
    - cust_vars.yml
  roles:
    - { role: splunk, tags: ["splunk"] }

- name: Install Splunk Heavy Forwarders
  hosts: heavy-forwarders
  vars_files:
    - cust_vars.yml
  roles:
    - { role: splunk_heavy_forwarder, tags: ["splunk"] }

- name: Install Splunk Universal Forwarders
  hosts: universal-forwarders
  vars_files:
    - cust_vars.yml
  roles:
    - { role: splunk_universal_forwarder, tags: ["splunk"] }

- name: Apply Splunk Syslog Configurations
  hosts: syslog-collector
  vars_files:
    - cust_vars.yml
  roles:
    - { role: syslog-ng, tags: ["splunk"] }
    - { role: splunk_syslog_inputs, tags: ["splunk"] }