
---
# Configures internal Splunk forwarders

- name: apply common configuration to all nodes
  hosts: all
  roles:
    - common_centos

- name: Install general syslog forwarder
  hosts: syslog-forwarders
  vars_files:
    - cust_vars.yml
  roles:
    - centos_splunk_forwarder
    - splunk_syslog