---

- set_fact: short_pkg_name={{ splunk_uf_installer_pkg | regex_replace('^(\w+-(?:\d|\.)+-\w+).*', '\\1') }}
- name: check if splunk is installed
  command: rpm -q {{ short_pkg_name }}
  register: pkg_status
  failed_when: false
  changed_when: false
  always_run: yes

- name: Create splunk installer folder
  file: path={{ install_source }}/ state=directory
  when: pkg_status.rc != 0

- name: Check for local copy of install package
  stat: path={{ install_source }}/{{ splunk_uf_installer_pkg }} get_md5=no
  register: forwarder_rpm
  always_run: yes

- name: Download Splunk package
  get_url: url={{ splunk_uf_fetch_url }} dest={{ install_source }}/
  when: pkg_status.rc != 0 and forwarder_rpm.stat.exists == False

- name: Install Splunk Package
  yum: name={{ install_source }}/{{ splunk_uf_installer_pkg }}
  register: forwarder_install
  when: pkg_status.rc != 0

- name: Drop in the user-seed.conf file
  template: src=user-seed.conf.j2 dest={{ splunk_uf_home }}/etc/system/local/user-seed.conf owner=splunk group=splunk mode=600
  when: forwarder_install.changed

- name: Start splunk for the first time
  command: "{{ splunk_uf_home }}/bin/splunk start --accept-license"
  when: forwarder_install.changed
  become: yes
  become_user: splunk

- name: Enable the Splunk Forwarder to run at boot time
  command: "{{ splunk_uf_home }}/bin/splunk enable boot-start -user splunk"
  when: forwarder_install.changed

# Check status of forwarding App
- name: Checking forwarding App
  shell: "{{ splunk_home }}/bin/splunk list app {{ send_to_forwarder_app | regex_replace('^(.*).spl$', '\\1') }} -auth admin:{{splunk_admin_pw}}"
  register: forwarder_app_status
  changed_when: False
  failed_when: False
  become: yes
  become_user: splunk
  always_run: yes

# Load App to configure forward-servers
- name: Load the Splunk Forwarder App
  copy: src={{ send_to_forwarder_app }} dest={{ install_source }}/
  when: forwarder_app_status.rc != 0

- name: Install forwarding App
  command: "{{ splunk_uf_home }}/bin/splunk install app {{ install_source }}/{{ send_to_forwarder_app }} -update 1 -auth admin:{{splunk_admin_pw}} creates={{ splunk_uf_home }}/etc/apps/{{ send_to_forwarder_app | regex_replace('^(.*).spl$', '\\1') }}/*"
  become: yes
  become_user: splunk
  notify:
  - restart splunk forwarder