---

# Create Splunk install source folder
- name: Create splunk installer folder
  file: path={{ install_source }}/ state=directory

# Download and install Splunk package
- name: Check Splunk package download
  stat: path={{ install_source }}/{{ splunk_installer_pkg }} get_md5=no
  register: forwarder_rpm

- name: Download Splunk package
  get_url: url={{ splunk_fetch_url }} dest={{ install_source }}/
  when: forwarder_rpm.stat.exists == False

- name: Install Splunk Package
  yum: name={{ install_source }}/{{ splunk_installer_pkg }}
  register: forwarder_install

- name: Drop in the user-seed.conf file
  template: src=user-seed.conf.j2 dest={{ splunk_home }}/etc/system/local/user-seed.conf owner=splunk group=splunk mode=600
  when: forwarder_install.changed

- name: Start splunk for the first time
  command: "{{ splunk_home }}/bin/splunk start --accept-license"
  when: forwarder_install.changed
  become: yes
  become_user: splunk

- name: Enable the Splunk Forwarder to run at boot time
  command: "{{ splunk_home }}/bin/splunk enable boot-start -user splunk"
  when: forwarder_install.changed

# Load App to configure forward-servers
- name: Load the Splunk Forwarder App
  copy: src={{ send_to_forwarder_app }} dest={{ install_source }}/ 

- name: Install forwarding App
  command: "{{ splunk_home }}/bin/splunk install app {{ install_source }}/{{ send_to_forwarder_app }} -update 1 -auth admin:{{splunk_admin_pw}} creates={{ splunk_home }}/etc/apps/{{ send_to_forwarder_app | regex_replace('^(.*).spl$', '\\1') }}/*"
  become: yes
  become_user: splunk
  notify:
  - restart splunk forwarder