---
# handlers file for Splunk

- name: restart splunk
  command: "{{ splunk_home }}/bin/splunk restart"
  become: yes
  become_user: splunk

- name: restart firewalld
  service: name=firewalld state=restarted