---

# Check / configure firewalld
- name: Check status of firewalld
  shell: "if service firewalld status | grep -q running; then echo true; else echo false; fi;"
  changed_when: False
  register: firewalld_status
  always_run: yes

# Open ports on firewalld
- name: Open firewalld ports
  firewalld: zone=public port={{ item }} permanent=true state=enabled
  notify: restart firewalld
  with_items:
    - 514/udp
    - 10514/udp
    - 10514/tcp
  when: firewalld_status.stdout == "true"

# Drop in our input configuration
- name: Create Splunk syslog app folder
  file: path={{ splunk_home }}/etc/apps/syslog/default state=directory owner=splunk group=splunk mode=755

- name: Load syslog inputs.conf
  template: src=default_inputs.conf.j2 dest={{ splunk_home }}/etc/apps/syslog/default/inputs.conf owner=splunk group=splunk mode=600
  notify:
  - restart splunk forwarder

- name: Load syslog props.conf
  copy: src=syslog_default_props.conf dest={{ splunk_home }}/etc/apps/syslog/default/props.conf owner=splunk group=splunk mode=600
  notify:
  - restart splunk forwarder

- name: Load syslog transforms.conf
  copy: src=syslog_default_transforms.conf dest={{ splunk_home }}/etc/apps/syslog/default/transforms.conf owner=splunk group=splunk mode=600
  notify:
  - restart splunk forwarder